version: "3"
services:

    postgres:
        image: postgres
        hostname: postgres
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: P@ssw0rd!

    my-first-go-rest-api:
        image: my-first-go-rest-api
        build:
            context: .
            dockerfile: dockerfile
        hostname: my-first-go-rest-api
        container_name: my-first-go-rest-api
        depends_on:
            - postgres
        ports:
            - 8080:8080
        environment: 
            db_user: postgres
            db_pass: P@ssw0rd!
            db_name: postgres
            db_host: postgres
            db_port: 5432
            token_password: dev_token_password